// ─── Contract ABIs used by the current frontend scope ─────────────────

import { parseAbi } from 'viem';

export const ABIS = {
    // Standard ERC-20
    ERC20: parseAbi([
        'function balanceOf(address owner) view returns (uint256)',
        'function allowance(address owner, address spender) view returns (uint256)',
        'function approve(address spender, uint256 amount) returns (bool)',
        'function transfer(address to, uint256 amount) returns (bool)',
        'function transferFrom(address from, address to, uint256 amount) returns (bool)',
        'function symbol() view returns (string)',
        'function decimals() view returns (uint8)',
        'function totalSupply() view returns (uint256)',
    ]),

    // MockAsset
    MOCK_ASSET: parseAbi([
        'function balanceOf(address owner) view returns (uint256)',
        'function allowance(address owner, address spender) view returns (uint256)',
        'function approve(address spender, uint256 amount) returns (bool)',
        'function mint(address to, uint256 amount) external',
        'function decimals() view returns (uint8)',
        'function symbol() view returns (string)',
        'function name() view returns (string)',
    ]),

    KREDIO_LENDING: parseAbi([
        'function admin() view returns (address)',
        'function totalDeposited() view returns (uint256)',
        'function totalBorrowed() view returns (uint256)',
        'function protocolFees() view returns (uint256)',
        'function utilizationRate() view returns (uint256)',
        'function depositBalance(address user) view returns (uint256)',
        'function collateralBalance(address user) view returns (uint256)',
        'function repaymentCount(address user) view returns (uint64)',
        'function defaultCount(address user) view returns (uint64)',
        'function pendingYield(address user) view returns (uint256)',
        'function getScore(address user) view returns (uint64 score, uint8 tier, uint32 collateralRatioBps, uint32 interestRateBps)',
        'function getPositionFull(address borrower) view returns (uint256 collateral, uint256 debt, uint256 accrued, uint256 totalOwed, uint32 interestBps, uint8 tier, bool active)',
        'function healthRatio(address borrower) view returns (uint256)',
        'function deposit(uint256 amount) external',
        'function withdraw(uint256 amount) external',
        'function pendingYieldAndHarvest(address user) external',
        'function depositCollateral(uint256 amount) external',
        'function withdrawCollateral() external',
        'function borrow(uint256 amount) external',
        'function repay() external',
        'function liquidate(address borrower) external',
        'function adminLiquidate(address borrower) external',
        'function setDemoMultiplier(address borrower, uint256 multiplier) external',
        'function sweepProtocolFees(address to) external',
        'event Borrowed(address indexed user, uint256 amount, uint8 tier, uint32 ratioBps)',
    ]),

    KREDIO_PAS_MARKET: parseAbi([
        'function owner() view returns (address)',
        'function ltvBps() view returns (uint256)',
        'function liqBonusBps() view returns (uint256)',
        'function stalenessLimit() view returns (uint256)',
        'function protocolFeeBps() view returns (uint256)',
        'function totalDeposited() view returns (uint256)',
        'function totalBorrowed() view returns (uint256)',
        'function protocolFees() view returns (uint256)',
        'function utilizationRate() view returns (uint256)',
        'function depositBalance(address user) view returns (uint256)',
        'function collateralBalance(address user) view returns (uint256)',
        'function repaymentCount(address user) view returns (uint256)',
        'function defaultCount(address user) view returns (uint256)',
        'function pendingYield(address user) view returns (uint256)',
        'function healthRatio(address borrower) view returns (uint256)',
        'function accruedInterest(address borrower) view returns (uint256)',
        'function maxBorrowable(address borrower) view returns (uint256)',
        'function getPositionFull(address borrower) view returns (uint256 collateralPAS, uint256 collateralValueUSDC, uint256 debtUSDC, uint256 accrued, uint256 totalOwed, uint32 interestBps, uint8 tier, bool active)',
        'function deposit(uint256 amount) external',
        'function withdraw(uint256 amount) external',
        'function pendingYieldAndHarvest(address user) external',
        'function depositCollateral() payable',
        'function withdrawCollateral() external',
        'function borrow(uint256 amount) external',
        'function repay() external',
        'function liquidate(address borrower) external',
        'function adminLiquidate(address borrower) external',
        'function sweepProtocolFees(address to) external',
        'function setOracle(address newOracle) external',
        'function setRiskParams(uint256 _ltvBps, uint256 _liqBonusBps, uint256 _stalenessLimit, uint256 _protocolFeeBps) external',
        'function setDemoMultiplier(address user, uint256 multiplier) external',
        'function pause() external',
        'function unpause() external',
        'event Borrowed(address indexed borrower, uint256 usdcAmount)',
    ]),

    PAS_ORACLE: parseAbi([
        'function latestRoundData() view returns (uint80, int256, uint256, uint256, uint80)',
        'function decimals() view returns (uint8)',
        'function isCrashed() view returns (bool)',
        'function setPrice(int256 price) external',
        'function crash(int256 crashPrice) external',
        'function recover() external',
    ]),

    GOVERNANCE_CACHE: parseAbi([
        'function getGovernanceData(address user) view returns (uint64 votes, uint8 conviction, uint256 cachedAt)',
        'function setGovernanceData(address user, uint64 voteCount, uint8 maxConviction) external',
        'function admin() view returns (address)',
    ]),
};
